
///This file is automatically generated. DO NOT EDIT, all your changes would be lost.
class AppAssets {
  AppAssets._();

  static const String appleLogo = 'assets/images/apple_logo.svg';
  static const String banner = 'assets/images/banner.png';
  static const String cart = 'assets/icons/cart.svg';
  static const String creditCard = 'assets/icons/credit_card.svg';
  static const String deliveryAddress = 'assets/icons/delivery_address.svg';
  static const String dymmyCategory = 'assets/images/dymmy_category.png';
  static const String dymmyNew = 'assets/images/dymmy_new.png';
  static const String dymmyPopular = 'assets/images/dymmy_popular.png';
  static const String dymmyProductDetails = 'assets/images/dymmy_product_details.png';
  static const String dymmySettings = 'assets/images/dymmy_settings.png';
  static const String favorite = 'assets/icons/favorite.svg';
  static const String googleLogo = 'assets/images/google_logo.svg';
  static const String home = 'assets/icons/home.svg';
  static const String instagram = 'assets/icons/instagram.svg';
  static const String location = 'assets/icons/location.svg';
  static const String logOut = 'assets/icons/log_out.svg';
  static const String logo = 'assets/images/logo.svg';
  static const String logoDarkPurple = 'assets/images/logo_dark_purple.svg';
  static const String mail = 'assets/icons/mail.svg';
  static const String messenger = 'assets/icons/messenger.svg';
  static const String money = 'assets/icons/money.svg';
  static const String notification = 'assets/icons/notification.svg';
  static const String orderDelivered = 'assets/icons/order_delivered.svg';
  static const String orderInProgress = 'assets/icons/order_in_progress.svg';
  static const String orderShipped = 'assets/icons/order_shipped.svg';
  static const String orderTrack = 'assets/icons/order_track.svg';
  static const String phoneNumberVerification = 'assets/images/phone_number_verification.svg';
  static const String points = 'assets/icons/points.svg';
  static const String profile = 'assets/icons/profile.svg';
  static const String resetPassword = 'assets/images/reset_password.svg';
  static const String search = 'assets/icons/search.svg';
  static const String settings = 'assets/icons/settings.svg';
  static const String share = 'assets/icons/share.svg';
  static const String shopping = 'assets/icons/shopping.svg';
  static const String splash = 'assets/images/splash.png';
  static const String splashAndroid12 = 'assets/images/splash_android_12.png';
  static const String verificationCode = 'assets/images/verification_code.svg';
  static const String whatsapp = 'assets/icons/whatsapp.svg';
  static const String emptyNotificationSVG = 'assets/images/empty_notification.svg';
  static const String emptySearchSVG = 'assets/images/empty_search.svg';
  static const String emptyCartSVG = 'assets/images/empty_cart.svg';
  static const String emptyFavoriteSVG = 'assets/images/empty_favorite.svg';

}
