
///This file is automatically generated. DO NOT EDIT, all your changes would be lost.
class AppAssets {
  AppAssets._();

  //static const String appleLogo = 'assets/images/apple_logo.svg';
  static const String appLogo = 'assets/images/logo.png';
  static const String drawerLogo = 'assets/images/drawer_logo.png';

}
